config/routes.rb
Rails.application.routes.draw do

  get 'posts/new'

  get 'topics/new'

  root                    'static_pages#home'
  get 'admin' => 'adminspace#admin'
  get 'help'          =>  'static_pages#help'
  get 'about'         =>  'static_pages#about'
  get 'contact'       =>  'static_pages#contact'
  get 'signup'        =>  'users#new'
  get 'login'         =>  'sessions#new'
  post 'login'         =>  'sessions#create'
  delete 'logout'     =>  'sessions#destroy'
  resources :users
  resources :forums do
    resources :categories do
      resources :topics
    end
  end
  resources :posts
  resources :news

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %> 
<!DOCTYPE html>
<html>
<head>
	<title><%= yield(:title) %> | Magazine Student Website</title>
</head>
<body>
	<h1>About</h1>
	<p>
		This website is being created by Caleb Hopper as an EAST project.
	</p>
</body>
</html>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
<p>
	Contact me with help/suggestions/random things at chopper@mageast.com
</p>

app/views/static_pages/help.html.erb
<% provide(:title, "Help") %>
<!DOCTYPE html>
<html>
<head>
	<title><%= yield(:title) %> | Magazine Student Website</title>
</head>
<body>
	<h1>Help</h1>
	<p>
		This page is currently under construction.
		If you have suggestions, please email me at
		chopper@mageast.com.
	</p>
</body>
</html>

app/views/static_pages/home.html.erb
<% @news = News.last %>
<% if logged_in? %>
<div class="center jumbotron">
<h1>Welcome to the Magazine Student Website</h1>
<h2>
	<%= render @news %>
</h2>
<%= link_to "Forums", forums_path, class: "btn btn-lg btn-primary" %>
<% else %>
<div class="center jumbotron">
<h1>Welcome to the Magazine Student Website</h1>
<h2>
	<%= render @news %>
</h2>
<%= link_to "Log in", login_path, class: "btn btn-lg btn-primary" %>
<%= link_to "Sign up", signup_path, class: "btn btn-lg btn-primary" %>
<% end %>
<% if logged_in? %>
<% if current_user.admin? %>
<%= link_to "Administrator space", admin_path, class: "btn btn-lg btn-primary" %>
<% end %>
<% end %>
</div>