config/routes.rb
Rails.application.routes.draw do

  get 'posts/new'

  get 'topics/new'

  root                    'static_pages#home'
  get 'admin' => 'adminspace#admin'
  get 'help'          =>  'static_pages#help'
  get 'about'         =>  'static_pages#about'
  get 'contact'       =>  'static_pages#contact'
  get 'signup'        =>  'users#new'
  get 'login'         =>  'sessions#new'
  post 'login'         =>  'sessions#create'
  delete 'logout'     =>  'sessions#destroy'
  resources :users
  resources :forums do
    resources :categories do
      resources :topics
    end
  end
  resources :posts
  resources :news

end

app/models/forum.rb
class Forum < ActiveRecord::Base
	has_many :categories
	validates :title, presence: true
	validates :description, presence: true
end

app/controllers/forums_controller.rb
class ForumsController < ApplicationController

  def index
    @forums = Forum.paginate(page: params[:page])
  end



  def show
  	@forum = Forum.find(params[:id])
    @categories = @forum.categories(params[:forum_id])
  end

  def new
  	@forum = Forum.new
  end

  def create
  	@forum = Forum.new(forum_params)
  	if @forum.save
  		flash[:success] = "Forum created."
  		redirect_to forums_path
  	else
  		render 'new'
  	end
  end

  private
  def forum_params
    params.require(:forum).permit(:title, :description)
  end
end

app/helpers/forums_helper.rb
module ForumsHelper
	def currentforum
		currentforum = Forum.find(params[:id])
	end
end

app/views/forums/_forum.html.erb
<li>
  <%= link_to forum.title, forum %>
</li>

app/views/forums/index.html.erb
<% provide(:title, 'All forums') %>
<span>
	<%= link_to "Forums", forums_path %>
</span>
<h1>All forums</h1>
<% if logged_in? %>
<% if current_user.admin? %>
<%= link_to "New Forum", new_forum_path, class: "btn btn-lg btn-primary" %>
<% end %>
<% end %>
<div class="center jumbotron">
<%= will_paginate %>

<ul class="forums">
  <% @forums.each do |forum| %>
    <li>
  		<%= link_to forum.title, forum %>
	</li>
  <% end %>
</ul>

<%= will_paginate %>
</div>

app/views/forums/new.html.erb
<% provide(:title, 'New Forum') %>
<h1>New Forum</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@forum) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.submit "Create Forum", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/forums/show.html.erb
<%= provide(:title, @forum.title) %>
<span>
	<%= link_to "Forums", forums_path %>
	/ <%= link_to @forum.title, forum_path(@forum.id) %>
</span>
<h1>
	<%= @forum.title %>
</h1>
<p>
	<%= @forum.description %>
</p>
<% if logged_in? %>
<% if current_user.admin? %>
<%= link_to "New Category", new_forum_category_path(@forum.id), class: "btn btn-lg btn-primary" %>
<% end %>
<% end %>
<div class="center jumbotron">

<ul class="categories">
  <% @categories.each do |category| %>
    <li>
  		<%= link_to category.title, forum_category_path(category.forum_id,category) %>
	</li>
  <% end %>
</ul>

</div>