config/routes.rb
Rails.application.routes.draw do

  get 'posts/new'

  get 'topics/new'

  root                    'static_pages#home'
  get 'admin' => 'adminspace#admin'
  get 'help'          =>  'static_pages#help'
  get 'about'         =>  'static_pages#about'
  get 'contact'       =>  'static_pages#contact'
  get 'signup'        =>  'users#new'
  get 'login'         =>  'sessions#new'
  post 'login'         =>  'sessions#create'
  delete 'logout'     =>  'sessions#destroy'
  resources :users
  resources :forums do
    resources :categories do
      resources :topics
    end
  end
  resources :posts
  resources :news

end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :forum
	has_many :topics
	validates :title, presence: true
	validates :description, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  include SessionsHelper
  before_action :admin_user, only: [:new, :create]

  def index
    @categories = Category.all.where("forum_id = ?", params[:forum_id])
  end

  def show
  	@category = Category.find(params[:id])
    @topics = @category.topics(params[:category_id])
    @forum = @category.forum
  end

  def new
    @forum = Forum.find(params[:forum_id])
  	@category = Category.new
  end

  def create
    @forum = Forum.find(params[:forum_id])
    @category = Category.new(category_params)
    @category.forum = @forum
  	if @category.save
  		flash[:success] = "Catergory created."
  		redirect_to forum_path(@forum.id)
  	else
  		render 'new'
  	end
  end

  private
  def category_params
    params.require(:category).permit(:title, :description)
  end

  def admin_user
    redirect_to(root_url) unless current_user.admin?
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper

end

app/views/categories/index.html.erb
<% provide(:title, 'All categories') %>
<h1>All categories</h1>

<div class="center jumbotron">

<ul class="categories">
  <% @categories.each do |category| %>
    <li>
  		<%= link_to category.title, forum_category_path(category.forum_id,category) %>
	</li>
  <% end %>
</ul>

</div>

app/views/categories/new.html.erb
<% provide(:title, 'New Category') %>
<h1>New Category</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for([@forum,@category]) do |f| %>
      <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :title %>
      <%= f.text_field :title, class: 'form-control' %>

      <%= f.label :description %>
      <%= f.text_area :description, class: 'form-control' %>

      <%= f.submit "Create Category", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/categories/show.html.erb
<%= provide(:title, @category.title) %>
<span>
  <%= link_to "Forums", forums_path %>
  / <%= link_to @category.forum.title, forum_path(@category.forum.id) %>
  / <%= link_to @category.title, forum_category_path(@category.forum.id, @category.id) %>
</span>
<h1>
	<%= @category.title %>
</h1>
<p>
	<%= @category.description %>
</p>
<% if logged_in? %>
<%= link_to "New Topic", new_forum_category_topic_path(@forum.id,@category.id), class: "btn btn-lg btn-primary" %>
<% end %>
<div class="center jumbotron">

<ul class="topics">
  <% @topics.each do |topic| %>
    <li>
  		<%= link_to topic.title, forum_category_topic_path(@forum.id,topic.category_id,topic.id) %>
      <% if logged_in? %>
      <% if current_user.admin? %>
    | <%= link_to "delete", forum_category_topic_path(@forum.id, topic.category_id, topic.id), method: :delete,
                                  data: { confirm: "You sure?" } %>
      <% end %>
      <% end %>
	</li>
  <% end %>
</ul>

</div>