config/routes.rb
Rails.application.routes.draw do

  get 'posts/new'

  get 'topics/new'

  root                    'static_pages#home'
  get 'admin' => 'adminspace#admin'
  get 'help'          =>  'static_pages#help'
  get 'about'         =>  'static_pages#about'
  get 'contact'       =>  'static_pages#contact'
  get 'signup'        =>  'users#new'
  get 'login'         =>  'sessions#new'
  post 'login'         =>  'sessions#create'
  delete 'logout'     =>  'sessions#destroy'
  resources :users
  resources :forums do
    resources :categories do
      resources :topics
    end
  end
  resources :posts
  resources :news

end

app/models/adminspace.rb
class Adminspace < ActiveRecord::Base
end

app/models/category.rb
class Category < ActiveRecord::Base
	belongs_to :forum
	has_many :topics
	validates :title, presence: true
	validates :description, presence: true
end

app/models/catergory.rb
class Catergory < ActiveRecord::Base
	belongs_to :forum
	has_many :topics
	validates :title, presence: true
	validates :description, presence: true
end

app/models/forum.rb
class Forum < ActiveRecord::Base
	has_many :categories
	validates :title, presence: true
	validates :description, presence: true
end

app/models/news.rb
class News < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
	belongs_to :topic
	default_scope -> { order(created_at: :asc)}
end

app/models/topic.rb
class Topic < ActiveRecord::Base
	belongs_to :category
	has_many :posts, :dependent => :destroy
	validates :title, presence: true
	validates :description, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token
	before_save :downcase_email
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
    has_secure_password
    validates :password, presence:true, length:{ minimum: 6 }, allow_nil: true

    def User.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
    												  BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
    end

    def User.new_token
    	SecureRandom.urlsafe_base64
    end

    def remember
    	self.remember_token = User.new_token
    	update_attribute(:remember_digest, User.digest(remember_token))
    end

    def authenticated?(remember_token)
    	return false if remember_digest.nil?
    	BCrypt::Password.new(remember_digest).is_password?(remember_token)
    end

    def forget
    	update_attribute(:remember_digest, nil)
    end

    private

    def downcase_email
        self.email = email.downcase
    end

    has_many :posts, :dependent => :destroy
end

app/controllers/news_controller.rb
class NewsController < ApplicationController
	def new
		@news = News.new
	end

	 def create
  	@news = News.new(news_params)
  	if @news.save
  		flash[:success] = "News created."
  		redirect_to admin_path
  	else
  		render 'new'
  	end
  end
  private
  def news_params
    params.require(:news).permit(:content)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
    include SessionsHelper

	before_action :logged_in_user, only: [:create, :destroy]

  def destroy
    @forum = Forum.find(params[:forum_id])
    @category = @forum.categories.find(params[:category_id])
    @topic = @category.topics.find(params[:topic_id])
    Post.find(params[:id]).destroy
    flash[:success] = "Post deleted."
    redirect_to forum_category_topic_path(@forum, @category, @topic)
  end

  def create
    #user = current_user
    #topic = params[:topic]
    #content = params[:content]

    #@post = Post.new
    #@post.user = user
    #@post.topic = topic
    #@post.content = content

  	@post = current_user.posts.build(post_params)
    if @post.save
      flash[:success] = "Post created!"
      redirect_to :back
    else
      render 'static_pages/home'
    end
  end

  def destroy
    Post.find(params[:id]).destroy
        flash[:success] = "Post deleted."
        redirect_to :back
  end

  def admin
    @admin = current_user.admin?
  end

  private

  	def post_params
      params.require(:post).permit(:content, :topic_id)
    end
end
#I needed a change to push, so here.

app/helpers/adminspace_helper.rb
module AdminspaceHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def full_title(page_title = '')
		base_title = "Magazine Student Website"
		if page_title.empty?
			base_title
		else
			page_title + " | " + base_title
		end
	end
	def markdown(text)
  render_options = {
    # will remove from the output HTML tags inputted by user 
    filter_html:     true,
    # will insert <br /> tags in paragraphs where are newlines 
    # (ignored by default)
    hard_wrap:       true, 
    # hash for extra link options, for example 'nofollow'
    link_attributes: { rel: 'nofollow' }
    # more
    # will remove <img> tags from output
    # no_images: true
    # will remove <a> tags from output
    # no_links: true
    # will remove <style> tags from output
    # no_styles: true
    # generate links for only safe protocols
    # safe_links_only: true
    # and more ... (prettify, with_toc_data, xhtml)
  }
  renderer = Redcarpet::Render::HTML.new(render_options)

  extensions = {
    #will parse links without need of enclosing them
    autolink:           true,
    # blocks delimited with 3 ` or ~ will be considered as code block. 
    # No need to indent.  You can provide language name too.
    # ```ruby
    # block of code
    # ```
    fenced_code_blocks: true,
    # will ignore standard require for empty lines surrounding HTML blocks
    lax_spacing:        true,
    # will not generate emphasis inside of words, for example no_emph_no
    no_intra_emphasis:  true,
    # will parse strikethrough from ~~, for example: ~~bad~~
    strikethrough:      true,
    # will parse superscript after ^, you can wrap superscript in () 
    superscript:        true
    # will require a space after # in defining headers
    # space_after_headers: true
  }
  Redcarpet::Markdown.new(renderer, extensions).render(text).html_safe
end
end

app/helpers/categories_helper.rb
module CategoriesHelper

end

app/helpers/forums_helper.rb
module ForumsHelper
	def currentforum
		currentforum = Forum.find(params[:id])
	end
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

	def log_in(user)
		session[:user_id] = user.id
	end

	def remember(user)
		user.remember
		cookies.permanent.signed[:user_id] = user.id
		cookies.permanent[:remember_token] = user.remember_token
	end

	def current_user?(user)
		user == current_user
	end

	def current_user
		if (user_id = session[:user_id])
      		@current_user ||= User.find_by(id: user_id)
    	elsif (user_id = cookies.signed[:user_id])
     		user = User.find_by(id: user_id)
      	if user && user.authenticated?(cookies[:remember_token])
        	log_in user
        	@current_user = user
      	end
    end
	end

	def logged_in?
		!current_user.nil?
	end

	def forget(user)
		user.forget
		cookies.delete(:user_id)
		cookies.delete(:remember_token)
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end

	def redirect_back_or(default)
		redirect_to(session[:forwarding_url] || default)
		session.delete(:forwarding_url)
	end

	def store_location
		session[:forwarding_url] = request.url if request.get?
	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def gravatar_for(user, options = {size: 80})
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
	<small>
		The Magazine Student Website by Caleb Hopper
	</small>
	<nav>
		<ul>
			<li><%= link_to "About", about_path %></li>
			<li><%= link_to "Contact", contact_path %></li>
			<li><a href="http://magazinerattlers.k12.ar.us/">Magazine School District Homepage</a></li>
		</ul>
	</nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "magsite", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home",   root_path %></li>
        <li><%= link_to "Help",   help_path %></li>
        <% if logged_in? %>
          <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li><%= link_to "Forums", forums_path %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
	<scripe src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="container">
	<% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
	<%= yield %>
	<%= render 'layouts/footer' %>
	<%= debug(params) if Rails.env.development?  %>
</div>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_news_form.html.erb
<%= form_for(@news) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new news..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_post_form.html.erb
<%= form_for(@post) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new post..." %>
    <%= f.hidden_field(:topic_id, value: locals[:topic_id]) %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>